x = float(input('Uma distância em metros: '))
print(f'Uma distância de {x:.1f}m corresponde a:')
print(f'{x/1000}km')
print(f'{x/100}hm')
print(f'{x/10}dam')
print(f'{x*10:.0f}dm')
print(f'{x*100:.0f}cm')
print(f'{x*1000:.0f}mm')